
/* Transform raw data and store into ANALYTICS schema in a new table*/

CREATE OR REPLACE TABLE ANALYTICS.EMPLOYEES AS

SELECT 
   TRIM(EMPLOYEE_ID) AS EMPLOYEE_ID,
    INITCAP(NULLIF(TRIM(FIRST_NAME),'')) AS FIRST_NAME,
    INITCAP(NULLIF(TRIM(LAST_NAME),'')) AS LAST_NAME,
    LOWER(COALESCE(NULLIF(TRIM(EMAIL),''),'manager@hotmail.com')) AS EMAIL,
    NULLIF(REGEXP_REPLACE(TRIM(PHONE), '[^0-9]', ''),'') AS PHONE,
    COALESCE(NULLIF(TRIM(DEPARTMENT_ID),''),'D1000') AS DEPARTMENT_ID,
    INITCAP(NULLIF(TRIM(JOB_TITLE),'')) AS JOB_TITLE,
    TRY_TO_DATE(TRIM(HIRE_DATE),'DD-MM-YYYY') AS HIRE_DATE,
    TRIM(SALARY) AS SALARY,
    NULLIF(TRIM(MANAGER_ID),'') AS MANAGER_ID,
    INITCAP(NULLIF(TRIM(GENDER),'')) AS GENDER,
    TRY_TO_DATE(NULLIF(TRIM(DOB),''),'DD-MM-YYYY')  AS DOB,
    NULLIF(TRIM(STATUS),'') AS STATUS,
    NULLIF(TRIM(WORK_LOACTION),'') AS WORK_LOACTION

FROM RAW.EMPLOYEES

SELECT * FROM EMPLOYEES;



/* TO CHECK COLUMNS DATA TYPES OF TABLE */
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EMPLOYEES'; -- Your table Name

SELECT COUNT(*) AS TOTAL FROM EMPLOYEES
